using UnityEngine;
using UnityEngine.UI;
using extOSC;

[DefaultExecutionOrder(-1)]
public class GameManager : MonoBehaviour
{
    private int etatEnMemoire = 1; // Le code initalise l'état initial du bouton comme relâché
    public extOSC.OSCReceiver oscReceiver;
    public static float Proportion(float value, float inputMin, float inputMax, float outputMin, float outputMax)
    {
        return Mathf.Clamp(((value - inputMin) / (inputMax - inputMin) * (outputMax - outputMin) + outputMin), outputMin, outputMax);
    }
    void TraiterOscKeyunit(OSCMessage message)
    {
        // Si le message n'a pas d'argument ou l'argument n'est pas un Int on l'ignore
        if (message.Values.Count == 0)
        {
            Debug.Log("No value in OSC message");
            return;
        }

        if (message.Values[0].Type != OSCValueType.Int)
        {
            Debug.Log("Value in message is not an Int");
            return;
        }

        // Récupérer la valeur de l’angle depuis le message OSC
        int nouveauEtat = message.Values[0].IntValue; // REMPLACER ici les ... par le code qui permet de récuérer la nouvelle donnée du flux
        if (etatEnMemoire != nouveauEtat) { // Le code compare le nouvel etat avec l'etat en mémoire
            etatEnMemoire = nouveauEtat; // Le code met à jour l'état mémorisé
            if ( nouveauEtat == 0 && !isPlaying ) {
                Play(); 
            } else {
                // METTRE ici le code pour lorsque le bouton est relaché
            }
        }

    }
    
    public static GameManager Instance { get; private set; }

    [SerializeField] private Player player;
    [SerializeField] private Spawner spawner;
    [SerializeField] private Parallax ground;
    [SerializeField] private Text scoreText;
   // [SerializeField] private GameObject playButton;
    [SerializeField] private GameObject gameOver;

    public int score { get; private set; } = 0;

    private bool isPlaying = false;

    private void Awake()
    {
        if (Instance != null) {
            DestroyImmediate(gameObject);
        } else {
            Instance = this;
        }
    }

    private void OnDestroy()
    {
        if (Instance == this) {
            Instance = null;
        }
    }

    public bool IsPlaying() {
        return isPlaying;
    }

    private void Start()
    {
        oscReceiver.Bind("/Keyunit", TraiterOscKeyunit);
        Stop();
    }

    public void Stop()
    {
        //Time.timeScale = 0f;
        player.enabled = false;
        spawner.enabled = false;
        ground.enabled = false;
        Pipes[] pipes = FindObjectsOfType<Pipes>();

        for (int i = 0; i < pipes.Length; i++) {
            pipes[i].enabled = false;
        }

        isPlaying = false;
    }

    public void Play()
    {
        score = 0;
        scoreText.text = score.ToString();

        //playButton.SetActive(false);
        gameOver.SetActive(false);

        //Time.timeScale = 1f;
        player.enabled = true;
        spawner.enabled = true;
        ground.enabled = true;

        Pipes[] pipes = FindObjectsOfType<Pipes>();

        for (int i = 0; i < pipes.Length; i++) {
            Destroy(pipes[i].gameObject);
        }

        isPlaying = true;
    }

    public void GameOver()
    {
        //.SetActive(true);
        gameOver.SetActive(true);

        Stop();
    }

    public void IncreaseScore()
    {
        score++;
        scoreText.text = score.ToString();
    }

    public void Update()
    {
        if (!isPlaying && (Input.GetKeyDown(KeyCode.Space) || Input.GetMouseButtonDown(0))) {
            Play();
        }
    }

}
